apiVersion: v1
kind: Pod
metadata:
  name: fdb-prometheus-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
spec:
  containers:
    - image: pierrezemb/fdb-prometheus-exporter:latest
      name: fdb-prometheus-exporter
      imagePullPolicy: always
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      env:
        - name: FDB_CLUSTER_FILE
          value: /mnt/config-volume/cluster-file
        - name: FDB_METRICS_EVERY
          value: "2"
      volumeMounts:
      - name: config-volume
        mountPath: /mnt/config-volume
  volumes:
    - name: config-volume
      configMap:
        name: sample-cluster-config